module.exports = {
  apps: [
    {
      name: 'scum-bot',
      script: 'src/bot.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        BOT_ENABLE_SCUM_WEBHOOK: 'true',
        BOT_ENABLE_RESTART_SCHEDULER: 'true',
        BOT_ENABLE_ADMIN_WEB: 'false',
        BOT_ENABLE_RENTBIKE_SERVICE: 'false',
        BOT_ENABLE_DELIVERY_WORKER: 'false',
        BOT_ENABLE_OPS_ALERT_ROUTE: 'true',
        BOT_HEALTH_HOST: '127.0.0.1',
        BOT_HEALTH_PORT: '3210',
      },
    },
    {
      name: 'scum-admin-web',
      script: 'apps/admin-web/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        BOT_ENABLE_ADMIN_WEB: 'true',
        ADMIN_WEB_SECURE_COOKIE: 'true',
        ADMIN_WEB_ENFORCE_ORIGIN_CHECK: 'true',
      },
    },
    {
      name: 'scum-worker',
      script: 'src/worker.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        WORKER_ENABLE_RENTBIKE: 'true',
        WORKER_ENABLE_DELIVERY: 'true',
        WORKER_HEARTBEAT_MS: '60000',
        WORKER_HEALTH_HOST: '127.0.0.1',
        WORKER_HEALTH_PORT: '3211',
      },
    },
    {
      name: 'scum-watcher',
      script: 'src/services/scumLogWatcherRuntime.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_WATCHER_HEALTH_HOST: '127.0.0.1',
        SCUM_WATCHER_HEALTH_PORT: '3212',
      },
    },
    {
      name: 'scum-server-bot',
      script: 'apps/server-bot/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_SERVER_BOT_HEALTH_HOST: '127.0.0.1',
        SCUM_SERVER_BOT_HEALTH_PORT: '3214',
      },
    },
    {
      name: 'scum-console-agent',
      script: 'src/scum-console-agent.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_CONSOLE_AGENT_HOST: '127.0.0.1',
        SCUM_CONSOLE_AGENT_PORT: '3213',
      },
    },
    {
      name: 'scum-web-portal',
      script: 'apps/web-portal-standalone/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        WEB_PORTAL_SECURE_COOKIE: 'true',
        WEB_PORTAL_ENFORCE_ORIGIN_CHECK: 'true',
      },
    },
  ],
};
