module.exports = {
  apps: [
    {
      name: 'scum-watcher',
      script: 'src/services/scumLogWatcherRuntime.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_WATCHER_HEALTH_HOST: '127.0.0.1',
        SCUM_WATCHER_HEALTH_PORT: '3212',
      },
    },
    {
      name: 'scum-server-bot',
      script: 'apps/server-bot/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_SERVER_BOT_HEALTH_HOST: '127.0.0.1',
        SCUM_SERVER_BOT_HEALTH_PORT: '3214',
      },
    },
    {
      name: 'scum-console-agent',
      script: 'src/scum-console-agent.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        SCUM_CONSOLE_AGENT_HOST: '0.0.0.0',
        SCUM_CONSOLE_AGENT_PORT: '3213',
      },
    },
  ],
};
